---
title: Global Influenza Trends 
---

### Team Members
  * Thomas Carpino (tc2899)
  * George Keefer (gwk2111)
  * Matthew Perrotta (mp3653)
  * Elliot Rozen (er2867)
  
<iframe width="560" height="315" src="https://www.youtube.com/embed/TGu4ZE2pQ5A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

###Project Scope

The primary objective of this project and endeavour is to explore the tools necessary to work in the intersection of infectious disease epidemiology modeling and data science. Specifically, we wanted to examime the seasonality of inlfuenza in different regions in the world using country level influenza data.

###Data

The following data was obtained from The WHO FLunet. We queried data from all 18 influenza transmission zones from year 2008 thru 2014.  In order to to calculate rates, we needed population data for each zone, which we obtained from the World Bank.  

###Exploratory Analysis

For our exploratory analysis, we looked at the the number of cases world wide by type and subtype, and then looked at the seasonality of cases based on influenza transmission zone.  We were curious to see if zones in the northern and southern hemisphere would differ.  We also were able to visualize the 2009 H1N1 pandemic.  View the visualizations from our analysis [here](Exploratory_Analysis.html).

###Epidemic Threshold

We fit an epidemic threshold curve for each of our chosen transmission zones in order to see when these regions have epidemics.  We decided to use a serfling regression model to estimate our curve.  We modeled a threshold based on CDC protocols, and were able to show how seasonality and transmission zone affect the [threshold](threshboard.html).  

### Important Information and Links 

More information about the team can be found in the [Team](Experience.html) tab. 

The Key Findings for the report can be found below. The full report can be found in the [Report](report.html) tab.

For the Repository utilized to construct the website can be found accessed [here](https://github.com/er2867/fluproject). The Repository utilized for data analysis and including our group's report can be accessed [here](https://github.com/mattperrotta/final_project)

Our data files for this project can be found [here](https://drive.google.com/drive/folders/1FcazPStI8FsAdQDWsujyn_jsFByolMC0?usp=sharing).


### Website Creation 

Information about this website was created can be found under the [About the Site](about.html) tab. 