---
title: "Report"
---

This is our Key Findings from our Final Report. 

**Motivation:**
The primary objective of this project and endeavour is to explore the tools necessary to work in the intersection of infectious disease epidemiology modeling and data science. In fact, the four team members are a part of Mailman's Infectious Disease Epidemiology Concentration. 

In exploring project ideas, we discussed feasability through the lens of data availability and our current knowledge of the field. The following includes some of our preliminary findings. 

Last year, in 2018, nearly 80,000 people died from the flu in the US alone according to [this CNN article](https://www.cnn.com/2018/09/26/health/flu-deaths-2017--2018-cdc-bn/index.html). In fact, many scholars argue that there is an impending 'global threat of avian flu' due to rapid globalization and urbanization. 

We find that understanding current patterns and trends of flu would be useful to build stronger epidemiological frameworks for disease surveillance and emergency preparedness. Specifically, we wanted to examime the seasonality of inlfuenza in different regions in the world using country level influenza data.  

**Related work:** 
Work on infectious disease modeling that was extremely interesting to us included the discussion about historic Methods for current statistical analysis of excess pneumonia-influenza deaths, found in [this NCBI article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1915276/). Additionally, the discussion during P8105 class (Data Science 1) about Google Flu Trends further inspired this exciting project. 

**Initial questions:**
What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?

**Data:**
We pulled our data directly from the website of different sources via CSV files from _[The WHO FluNet](http://apps.who.int/flumart/Default?ReportNo=12)_, the _[The WHO General Health Observatory data repository](http://apps.who.int/gho/data/node.main.HWF10?lang=en)_, and the _[The World Bank Open Data](http://apps.who.int/gho/data/node.main.HWF10?lang=en)_. 

We scraped demographic data from the _[CIA World Factbook](https://www.cia.gov/library/publications/the-world-factbook/)_, but eventually decided this data would not be used in our final report and analyses. 

**Exploratory analysis:** 
Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.

We visualized the number of infections from each of the different zones, and then selected zones which had the most rigorous data available, including ___. 

We ran a regression to calculate an epidemic threshold curve for each influenza transmission zone that we selected. 

**Additional analysis:** 
If you undertake formal statistical analyses, describe these in detail

**Discussion:** 
What were your findings? Are they what you expect? What insights into the data can you make?

**Motivation:** 
All four of us are in the Infectious Disease Epidemiology Concentration and are interested in becoming aquainted with ID Epi modeling in R. 

Last year, in 2018, nearly 80,000 people died from the flu in the US alone. 

_Check out the article [here](https://www.cnn.com/2018/09/26/health/flu-deaths-2017--2018-cdc-bn/index.html)._

Many scholars argue that there is an impending 'global threat of avian flu' due to rapid globalization and urbanization. 

Understanding current patterns and trends of flu could be useful to build stronger epidemiological frameworks for disease surveillance and emergency preparedness. 

Specifically, we want to examime the seasonality of inlfuenza in different regions in the world using country level influenza data.  

Google flu trends

**Final products/Deliverables:**

Report, Statistical Analyses, Webpage, and Screencast

**Anticipated data sources:** 

_[The WHO FluNet](http://apps.who.int/flumart/Default?ReportNo=12)._

_[The WHO General Health Observatory data repository](http://apps.who.int/gho/data/node.main.HWF10?lang=en)._

_[The World Bank Open Data](http://apps.who.int/gho/data/node.main.HWF10?lang=en)._

_[CIA World Factbook](https://www.cia.gov/library/publications/the-world-factbook/)_ (For demographic data - obtained through scraping)

**Planned analyses:**

    * Logisitic Regression with outcome of epidemic threshold with interaction from various covariates
    * Linear Regression of rate vs seasonality
  
**Potential Indicators or Covariates:**

    * Country or Region
    * Time or Year
    * Strain
    * GDP
    * Urbanization
    
**Visualizations:**

    * Positive influenza cases over time, measured by year and epi week
    * Seasonal vs. pandemic influenza 
    * Seasonality of influenza by region and/or by strain
    
**Coding Challenges:**

A few coding challenges that we expect to face are the scale of the data, and lack of granularity.  The data is countrywide, and density and urbanization are possible confounders that we may not be able to control for.  There is also different sources for our data, which can pose challenges merging the datasets.  